# List of projects
set(PROJECT_LIST
    01_Window
    02_Tri
    03_Tri_W
    04_Color_Tri
    05_Text
    06_Text_Class
    07_3D_Geo
    08_Cube
    09_Camera
    10_Camera_Class
    11_Phong_Blinn
    12_LightMaps
    13_Directional_Light
    14_Point_Light
    15_Spot_Light
    16_All_Lights
    17_Load_Model
    18_Normal_Mapping
    19_FBO
    20_Post_Processing
    21_Shadow_Maps
    22_Actividad1_PhongBlinn_ViewSpace
    23_AllLights_PhongBlinn_ViewSpace
    24_AllLights_Phong_ViewSpace
    25_Actividad2_LookAt_Animation
    26_Actividad3_FlashLight_AllLights_ViewSpace
    27_ToggleFlashLight_AllLights_ViewSpace
    28_Sensitive_ToggleFlashLight_AllLights_ViewSpace
    29_ShadowMap_Sensitive_ToggleFlashLight_AllLights_ViewSpace
    30_Pyramids_ShadowMap_Sensitive_ToggleFlashLight_AllLights_ViewSpace
    31_NormalMapping_ShadowMap_Sensitive_ToggleFlashLight_AllLights_ViewSpace
    32_Shadow_Class_NormalMapping_ShadowMap_Sensitive_ToggleFlashLight_AllLights_ViewSpace
    33_Sun_Shadow_Class_NormalMapping_ShadowMap_Sensitive_ToggleFlashLight_AllLights_ViewSpace
    34_SmallCamera_Sun_Shadow_Class_NormalMapping_ShadowMap_Sensitive_ToggleFlashLight_AllLights_ViewSpace
    35_ViewPort_Sun_Shadow_Class_NormalMapping_ShadowMap_Sensitive_ToggleFlashLight_AllLights_ViewSpace
    36_ViewPort_Sun_Shadow_Class_NormalMapping_ShadowMap_Sensitive_ToggleFlashLight_AllLights_ViewSpace
    37_Actividad5_FBO
    38_Horus_ViewPort_Sun_Shadow_Class_NormalMapping_ShadowMap_Sensitive_ToggleFlashLight_AllLights_ViewSpace
    39_Colors_Horus_ViewPort_Sun_Shadow_Class_NormalMapping_ShadowMap_Sensitive_ToggleFlashLight_AllLights_ViewSpace
    40_Actividad3_Horus
    41_DirectionalLight_Colors_Horus_ViewPort_Sun_Shadow_Class_NormalMapping_ShadowMap_Sensitive_ToggleFlashLight_AllLights_ViewSpace
    42_PointLight_PhongBlinn
    43_PointLight_GouraudPhongBlinn
    44_PointLight_Faceted
    45_PointLight_Difuse
    46_Shadow_PointLight_PhongBlinn
    47_Shadow_PointLight_GouraudPhongBlinn
    48_Shadow_PointLight_Faceted
    49_Shadow_PointLight_Difuse
    )